# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Yuki (Yingxue) Ao | BI DataViz"
weight = 1

[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "Yuki Ao的数据博客"
weight = 1