# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "linktree"
name = "Linktree"
url = "https://linktr.ee/datawilltell"

[social.params]
icon = "brand-linktree"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/aoyingxue"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/aoyingxue/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "tableau"
name = "Tableau Public"
url = "https://public.tableau.com/app/profile/yukiao/vizzes"

[social.params]
icon = "brand-tableau-software"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/datawilltell/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "threads"
name = "Instagram"
url = "https://www.threads.net/@datawilltell"

[social.params]
icon = "brand-threads"

[[social]]
identifier = "twitter"
name = "X/Twitter"
url = "https://twitter.com/datawilltell"

[social.params]
icon = "brand-twitter"
