# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Stack"
license = "GPL-3.0-only"
licenselink = "https://github.com/CaiJimmy/hugo-theme-stack/blob/master/LICENSE"
description = ""
homepage = "https://github.com/aoyingxue/hugo-theme-stack-for-datawilltell"
demosite = "https://demo.stack.jimmycai.com"

tags = ["blog", "responsive", "clean", "light", "dark", "personal"]

features = [
    "disqus",
    "photoswipe",
    "opengraph",
    "widgets",
    "darkmode",
    "table of contents",
    "search",
]

min_version = "0.123.0"

[original]
name = "Jimmy Cai"
homepage = "https://jimmycai.com"
repo = "https://github.com/CaiJimmy/hugo-theme-stack"